#!/usr/bin/env bash

#######################################
#  __  .__                            #
#_/  |_|  |__   ____   _____   ____   #
#\   __\  |  \_/ __ \ /     \_/ __ \  #
# |  | |   Y  \  ___/|  Y Y  \  ___/  #
# |__| |___|  /\___  >__|_|  /\___  > #
#           \/     \/      \/     \/  #
#######################################
hc() {
    herbstclient "$@"
}

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

hc set frame_border_width 0
hc set always_show_frame 0
hc set frame_bg_transparent 0
hc set frame_transparent_width 0
hc set frame_gap 18
hc set window_gap 6

hc set frame_bg active color black
hc set frame_bg normal color black
hc set frame_active_opacity 10
hc set frame_normal_opacity 10

hc attr theme.urgent.color orange
hc attr theme.inner_width 0
hc attr theme.outer_width 8
hc attr theme.border_width 8
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 0
hc attr theme.floating.outer_color black
hc attr theme.active.outer_color '#d75f00'
hc attr theme.normal.outer_color '#0087af'
hc attr theme.inner_width 8

hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

feh --bg-fill ~/Pictures/Wallpapers/matwalp.jpg
